#!/bin/sh


git clone https://gitlab.com/marcusbritanicus/libarchive-qt.git
git clone https://gitlab.com/extraqt/qdocumentview.git

git clone https://gitlab.com/cubocore/libcprime.git
git clone https://gitlab.com/cubocore/libcsys.git

git clone https://gitlab.com/cubocore/coreapps/coreaction.git
git clone https://gitlab.com/cubocore/coreapps/corearchiver.git
git clone https://gitlab.com/cubocore/coreapps/corefm.git
git clone https://gitlab.com/cubocore/coreapps/coregarage.git
git clone https://gitlab.com/cubocore/coreapps/corehunt.git
git clone https://gitlab.com/cubocore/coreapps/coreimage.git
git clone https://gitlab.com/cubocore/coreapps/coreinfo.git
git clone https://gitlab.com/cubocore/coreapps/corekeyboard.git
git clone https://gitlab.com/cubocore/coreapps/corepad.git
git clone https://gitlab.com/cubocore/coreapps/corepaint.git
git clone https://gitlab.com/cubocore/coreapps/corepdf.git
git clone https://gitlab.com/cubocore/coreapps/corepins.git
git clone https://gitlab.com/cubocore/coreapps/corerenamer.git
git clone https://gitlab.com/cubocore/coreapps/coreshot.git
git clone https://gitlab.com/cubocore/coreapps/corestats.git
git clone https://gitlab.com/cubocore/coreapps/corestuff.git
git clone https://gitlab.com/cubocore/coreapps/coreterminal.git
git clone https://gitlab.com/cubocore/coreapps/coretime.git
git clone https://gitlab.com/cubocore/coreapps/coretoppings.git
git clone https://gitlab.com/cubocore/coreapps/coreuniverse.git

echo "############### BUILDING libarchive-qt ###############"


# Build libarchive-qt
cd libarchive-qt
meson .build --prefix=/usr --buildtype=release -Duse_qt_version=qt6
ninja -C .build -k 0 -j $(nproc)
ninja -C .build install
cd ../



echo "############### BUILDING qdocumentview ###############"

# Build qdocumentview
cd qdocumentview
meson setup .build6 --prefix=/usr --buildtype=release -Duse_qt_version=qt6
ninja -C .build6 -j $(nproc) -k
ninja -C .build6 install
cd ../



echo "############### BUILDING libcsys ###############"

# Build libcsys
cd libcsys
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING libcprime ###############"


# Build libcprime
cd libcprime
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coreaction ###############"


# Build coreaction
cd coreaction
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corearchiver ###############"


# Build corearchiver
cd corearchiver
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corefm ###############"


# Build corefm
cd corefm
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coregarage ###############"


# Build coregarage
cd coregarage
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corehunt ###############"

# Build corehunt
cd corehunt
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coreimage ###############"


# Build coreimage
cd coreimage
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coreinfo ###############"


# Build coreinfo
cd coreinfo
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corekeyboard ###############"


# Build corekeyboard
cd corekeyboard
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corepad ###############"


# Build corepad
cd corepad
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corepaint ###############"


# Build corepaint
cd corepaint
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corepdf ###############"


# Build corepdf
cd corepdf
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corepins ###############"


# Build corepins
cd corepins
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corerenamer ###############"


# Build corerenamer
cd corerenamer
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coreshot ###############"


# Build coreshot
cd coreshot
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corestats ###############"


# Build corestats
cd corestats
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING corestuff ###############"


# Build corestuff
cd corestuff
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coreterminal ###############"


# Build coreterminal
cd coreterminal
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coretime ###############"


# Build coretime
cd coretime
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coretoppings ###############"


# Build coretoppings
cd coretoppings
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../



echo "############### BUILDING coreuniverse ###############"


# Build coreuniverse
cd coreuniverse
cmake -GNinja ./CMakeLists.txt
ninja -k 0 -j $(nproc) 
ninja install
cd ../

echo "############### BUILD COMPLETED ###############"

