name: Build C-Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:edge
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: ./alpine-depend
      - name: Compile
        run: ./compile

  build-archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: ./arch-depend
      - name: Compile
        run: ./compile

  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:sid
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: ./debian-depend
      - name: Compile
        run: ./compile